### ISSUE TITLE
Cusom Queries in Ionic2

### ISSUE THREAD

**Issue by georgechapman** [backand/backand-ionic2-starter#1]
Hi @kornatzky, thanks for the starter, has helped no end.

I have hit a bit of a roadblock after trying to expand on your code. I am trying to implement a custom query but not sure how to do so. The standard http.get command you have detailed looks like so:

```
return this.http.get(this.api_url + '/1/objects/items?returnObject=true', {
  headers: this.authHeader
})
.retry(3)
.map(res => res.json().data);
```

But if i have a custom query that has a Request $Http command as so how do I call it in a similar way to your http.get above in Ionic2/Angular2?

```
return $http ({
  method: 'GET',
  url: Backand.getApiUrl() + '/1/query/data/get_specific_data',
  params: {
    parameters: {
      a: 'foo',
      b: 'bar'
    }
  }
});
```

Many thanks in advance for any help you can provide.

Cheers
George

**Comment by kornatzky** [comment]
The way to do it is demonstrated in this function from the file app/services/backandServices.ts:

```
 public filterItems(query) {
        let filter = 
            [
              {
                fieldName: 'name',
                operator: 'contains',
                value: query
              }
            ]
        ;

        return this.http.get(this.api_url + '/1/objects/todo?filter=' + encodeURI(JSON.stringify(filter)), 
            {
                headers: this.authHeader
            })
            .retry(3)
            .map(res => res.json().data);
    }

```

As you can see in the CRUD tab as we filter with a search window.

**Comment by georgechapman** [comment]
That's great thanks, so how would this work with a location based query such as in the Backand documentation:

```
{
      "object": "restaurants",
      "q": {
         "location" : { "$withinMiles" : [[37.8019859, -122.4414805], 25] }
      }
  }
```

Could you use this same filter logic against an `/1/objects/restaurants` object with the `fieldName: 'location'` if so what would the `operator` and `value` attributes look like

**Comment by relly** [comment]
The filter parameter in GET objects '/1/objects/restaurants' can work in two ways
1. One way is with field, operator and value array like this 
[{fieldName: 'name',operator: 'contains',value: 'something'}]
2. The other is with a NoSQL condition, something like this
{
      "object": "restaurants",
      "q": {
         "name" : { "$like" : 'something' }
      }
  }
both ways are equivalent.
however for location you must only use the NoSQL way like in the example above and should look like this:

```
public filterLocation(point, miles) {
        let withinMiles = 
       {
              "q": {
                   "location" : { "$withinMiles" : [point, miles] }
                }
        }

        return this.http.get(this.api_url + '/1/objects/todo?filter=' + encodeURI(JSON.stringify(withinMiles)), 
            {
                headers: this.authHeader
            })
            .retry(3)
            .map(res => res.json().data);
    }
```

**Comment by georgechapman** [comment]
Thanks @relly and @kornatzky that's sorted it :+1: 

One last question; is there any way of sorting a `$withinMiles` query by distance from the point ASC or DESC?

Cheers

**Comment by kornatzky** [comment]
Currently we do not have the facility. But it is one of the things on our agenda.

**Comment by relly** [comment]
You can use Backand queries for that. Backand Query works for both SQL and NoSQL syntax.
You can read more at [the docs](http://docs.backand.com/en/latest/getting_started/queries/index.html).
Here is an example for the SQL that you may use:

`SELECT * FROM`restaurants`
WHERE (ST_Distance (`restaurants`.`location`, ST_GeomFromText('POINT( 37.8019859 -122.4414805 )') ) <= 25 /(69))
ORDER BY ST_Distance (`restaurants`.`location`, ST_GeomFromText('POINT( 37.8019859 -122.4414805 )') )`

It is a basic suggestion that I am sure you will improve. There is a lot of information how to work with MySQL and GEO Point, That is what we use in Backand.
I also suggest that you will send the point values as parameters to the query
You can see it in the [docs](http://docs.backand.com/en/latest/what_would_you_like_to_do/geo/#query-point-with-parameters) for NoSQL but it is the same as for SQL

**Comment by georgechapman** [comment]
That's brilliant thanks @relly 

It brings me back to my original point however as to how one executes a custom query, with input parameters, in an ionic2 app? Unfortunately I can't find any docs around this.

Many thanks
