### ISSUE TITLE
Following your readme this starter fails build process

### ISSUE THREAD

**Issue by florianbepunkt** [backand/backand-ionic2-starter#4]
Hi, just following your readme file, I get an error when building for ios:

```
$ ionic start myApp https://github.com/backand/backand-ionic2-starter --v2 cd myApp
$ ionic plugin add cordova-plugin-inappbrowser
$ npm install socket.io-client --save
$ ionic build ios
```

`$ ionic serve` works fine, but i get following build error… I did not modify any code in the starter. heres the console output. below I added the npm debug log. can you verify this happens on your end as well? As far as I see this has to do with socket.io

```
MacBook-Pro:myApp floriannorbertbepunkt$ ionic build ios

Running 'build:before' npm script before build
> ionic-hello-world@ build /Users/floriannorbertbepunkt/Dropbox/Dropbox Arbeit/Mister Bishop Studios/Ionic Tests/myApp
> ionic-app-scripts build
[23:29:19]  ionic-app-scripts 0.0.30
[23:29:19]  build prod started ...
[23:29:19]  clean started ...
[23:29:19]  clean finished in 3 ms
[23:29:19]  copy started ...
[23:29:19]  ngc started ...
[23:29:19]  lint started ...
[23:29:19]  copy finished in 49 ms
[23:29:20]  tslint: /Users/floriannorbertbepunkt/Dropbox/Dropbox Arbeit/Mister Bishop Studios/Ionic Tests/myApp/src/providers/backandService.ts[38, 21]: Unused import: 'BehaviorSubject'
/Users/floriannorbertbepunkt/Dropbox/Dropbox Arbeit/Mister Bishop Studios/Ionic Tests/myApp/src/providers/backandService.ts[39, 24]: Unused import: 'URLSearchParams'
/Users/floriannorbertbepunkt/Dropbox/Dropbox Arbeit/Mister Bishop Studios/Ionic Tests/myApp/src/providers/backandService.ts[66, 13]: Unused property: 'is_auth_error'
/Users/floriannorbertbepunkt/Dropbox/Dropbox Arbeit/Mister Bishop Studios/Ionic Tests/myApp/src/providers/backandService.ts[345, 17]: Unused variable: 'subscription'


[23:29:20]  lint finished in 932 ms
[23:29:28]  ngc: Error: Error at /Users/floriannorbertbepunkt/Dropbox/Dropbox Arbeit/Mister Bishop Studios/Ionic Tests/myApp/.tmp/providers/backandService.ts:72:21: Cannot find namespace 'SocketIOClient'.
    at check (/Users/floriannorbertbepunkt/Dropbox/Dropbox Arbeit/Mister Bishop Studios/Ionic Tests/myApp/node_modules/@angular/tsc-wrapped/src/tsc.js:31:15)
    at Tsc.typeCheck (/Users/floriannorbertbepunkt/Dropbox/Dropbox Arbeit/Mister Bishop Studios/Ionic Tests/myApp/node_modules/@angular/tsc-wrapped/src/tsc.js:86:9)
    at /Users/floriannorbertbepunkt/Dropbox/Dropbox Arbeit/Mister Bishop Studios/Ionic Tests/myApp/node_modules/@angular/tsc-wrapped/src/main.js:33:23
    at process._tickCallback (internal/process/next_tick.js:103:7)
    at Function.Module.runMain (module.js:449:11)
    at startup (node.js:148:18)
    at node.js:405:3


[23:29:28]  ngc: Compilation failed


[23:29:28]  ngc failed:  NGC encountered an error

[23:29:28]  Error: NGC encountered an error
    at ChildProcess.<anonymous> (/Users/floriannorbertbepunkt/Dropbox/Dropbox Arbeit/Mister Bishop Studios/Ionic Tests/myApp/node_modules/@ionic/app-scripts/dist/ngc.js:62:24)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at Pipe._onclose (net.js:484:12)

Error running ionic app script "build": Error: NGC encountered an error



npm
 ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/Cellar/node5/5.12.0/bin/node" "/usr/local/bin/npm" "run" "build"

npm ERR! node v5.12.0
npm ERR! npm  v3.10.8

npm ERR! code ELIFECYCLE
npm ERR!
 ionic-hello-world@ build: `ionic-app-scripts build`
npm ERR! Exit status 1
npm 
ERR! 
npm ERR! Failed at the ionic-hello-world@ build script 'ionic-app-scripts build'.
npm
 ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ionic-hello-world package,
npm 
ERR!
 not with npm itself.
npm ERR!
 Tell the author that this fails on your system:
npm ERR!     ionic-app-scripts build

npm ERR!
 You can get information on how to open an issue for this project with:
npm
 ERR!     npm bugs ionic-hello-world
npm ERR! Or if that isn't available, you can get their info via:
npm
 ERR!     npm owner ls ionic-hello-world

npm ERR! There is likely additional logging output above.



npm ERR! Please include the following file with any support request:
npm ERR!     /Users/floriannorbertbepunkt/Dropbox/Dropbox Arbeit/Mister Bishop Studios/Ionic Tests/myApp/npm-debug.log

Caught exception:
 undefined 

Mind letting us know? https://github.com/driftyco/ionic-cli/issues
```

here's my npm-debug.log

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node5/5.12.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@3.10.8
3 info using node@v5.12.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle ionic-hello-world@~prebuild: ionic-hello-world@
6 silly lifecycle ionic-hello-world@~prebuild: no script for prebuild, continuing
7 info lifecycle ionic-hello-world@~build: ionic-hello-world@
8 verbose lifecycle ionic-hello-world@~build: unsafe-perm in lifecycle true
9 verbose lifecycle ionic-hello-world@~build: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/floriannorbertbepunkt/Dropbox/Dropbox Arbeit/Mister Bishop Studios/Ionic Tests/myApp/node_modules/.bin:/usr/local/Cellar/node5/5.12.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin
10 verbose lifecycle ionic-hello-world@~build: CWD: /Users/floriannorbertbepunkt/Dropbox/Dropbox Arbeit/Mister Bishop Studios/Ionic Tests/myApp
11 silly lifecycle ionic-hello-world@~build: Args: [ '-c', 'ionic-app-scripts build' ]
12 silly lifecycle ionic-hello-world@~build: Returned: code: 1  signal: null
13 info lifecycle ionic-hello-world@~build: Failed to exec build script
14 verbose stack Error: ionic-hello-world@ build: `ionic-app-scripts build`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at EventEmitter.emit (events.js:185:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at ChildProcess.emit (events.js:185:7)
14 verbose stack     at maybeClose (internal/child_process.js:850:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid ionic-hello-world@
16 verbose cwd /Users/floriannorbertbepunkt/Dropbox/Dropbox Arbeit/Mister Bishop Studios/Ionic Tests/myApp
17 error Darwin 15.5.0
18 error argv "/usr/local/Cellar/node5/5.12.0/bin/node" "/usr/local/bin/npm" "run" "build"
19 error node v5.12.0
20 error npm  v3.10.8
21 error code ELIFECYCLE
22 error ionic-hello-world@ build: `ionic-app-scripts build`
22 error Exit status 1
23 error Failed at the ionic-hello-world@ build script 'ionic-app-scripts build'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the ionic-hello-world package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     ionic-app-scripts build
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs ionic-hello-world
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls ionic-hello-world
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

**Comment by kornatzky** [comment]
We have tried reproducing the issue and it does not occur. Note that you should upgrade Ionic to the latest. Your Typescript has to be the latest. 

Do the following: 

npm update -g ionic
npm update -g typescript 

We would also recommend updating cordova:
npm update -g cordova

Our environment:

kornatzkys-MacBook-Pro:myApp kornatzky$ ionic --version 
2.1.0
kornatzkys-MacBook-Pro:myApp kornatzky$ node --version 
v6.7.0
kornatzkys-MacBook-Pro:myApp kornatzky$ npm --version
3.10.8
kornatzkys-MacBook-Pro:myApp kornatzky$ cordova --version 
6.3.1
kornatzkys-MacBook-Pro:myApp kornatzky$ tsc --version 
Version 2.0.3

**Comment by florianbepunkt** [comment]
The issue still persists. I updated everything and now have the same versions installed as you do.
Still build fails.

Main error IMO is this

```
[11:15:47]  lint finished in 1.08 s
[11:15:56]  ngc: Error: Error at /Users/floriannorbertbepunkt/Dropbox/Dropbox Arbeit/Mister Bishop Studios/Ionic Tests/myApp/.tmp/providers/backandService.ts:72:21: Cannot find namespace 'SocketIOClient'.

```

**Comment by florianbepunkt** [comment]
If anyone else has this issue please change backandServce.ts line 72

from `private socket: SocketIOClient.Socket;;` to `private socket: any;`

not sure where the error lies though… have installed typings for socket.io, but maybe the wrong ones. or the type def in backendService.ts is wrong.

**Comment by kornatzky** [comment]
Try doing inside the project folder:

npm install @types/node --save-dev --save-exact
npm install @types/socket.io-client --save-dev --save-exact

**Comment by kornatzky** [comment]
Would appreciate your feedback. This should let you preserve your code without any change.

**Comment by florianbepunkt** [comment]
Thank you. This did the trick. Can you explain me briefly what happened?

As far as I understand, -exact foreced npm to install an exact typings version for socket.io? So before I had the wrong typings (?)

**Comment by kornatzky** [comment]
This is really weird. When I first constructed an example app, I also needed to do it. Later when we converted it to a starter and tried to produce an app from a starter, this was not needed. But in any case, given your issues, I would add it to the README. Thanks for the help.

**Comment by adirzoari** [comment]
@kornatzky @florianbepunkt i have the same error when i run ionic run android, i did exactly what you wrote and i still have the error

> 10:09:47]  ngc failed:  NGC encountered an error
> 
> [10:09:47]  Error: NGC encountered an error
>     at ChildProcess.<anonymous> (C:\Users\Adir\MyApps\tasklist\node_modules\@ionic\app-scripts\dist\ngc.js:62:24)
>     at emitTwo (events.js:106:13)
>     at ChildProcess.emit (events.js:191:7)
>     at ChildProcess.cp.emit (C:\Users\Adir\MyApps\tasklist\node_modules\cross-spawn\lib\enoent.js:40:29)
>     at maybeClose (internal/child_process.js:877:16)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
> 
> Error running ionic app script "build": Error: NGC encountered an error
> 
> npm
>  ERR! Windows_NT 10.0.14393
> npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Users\Adir\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js" "run" "build"
> npm
>  ERR! node v6.7.0
> npm ERR! npm  v3.10.8
> npm ERR! code ELIFECYCLE
> npm ERR! ionic-hello-world@ build: `ionic-app-scripts build --rollup ./config/rollup.config.js`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the ionic-hello-world@ build script 'ionic-app-scripts build --rollup ./config/rollup.config.js'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.

**Comment by florianbepunkt** [comment]
Can you post full console ouput and full npm log file?

**Comment by adirzoari** [comment]
> C:\Users\Adir\MyApps\tasklist>ionic run andorid
> 
> Running 'run:before' npm script before run
> 
> > ionic-hello-world@ build C:\Users\Adir\MyApps\tasklist
> > ionic-app-scripts build --rollup ./config/rollup.config.js
> > [10:09:35]  ionic-app-scripts 0.0.30
> > [10:09:35]  build prod started ...
> > [10:09:35]  clean started ...
> > [10:09:35]  clean finished in 38 ms
> > [10:09:35]  copy started ...
> > [10:09:35]  ngc started ...
> > [10:09:35]  lint started ...
> > [10:09:35]  copy finished in 152 ms
> > [10:09:36]  lint finished in 988 ms
> > [10:09:47]  ngc: Error: Error at C:/Users/Adir/MyApps/tasklist/.tmp/pages/login/login.ngfactory.ts:681:41: Property 'usersList' is private and only accessible within class 'LoginPage'.
> >     at check (C:\Users\Adir\MyApps\tasklist\node_modules\@angular\tsc-wrapped\src\tsc.js:31:15)
> >     at Tsc.typeCheck (C:\Users\Adir\MyApps\tasklist\node_modules\@angular\tsc-wrapped\src\tsc.js:86:9)
> >     at C:\Users\Adir\MyApps\tasklist\node_modules\@angular\tsc-wrapped\src\main.js:33:23
> >     at process._tickCallback (internal/process/next_tick.js:103:7)
> >     at Module.runMain (module.js:592:11)
> >     at run (bootstrap_node.js:394:7)
> >     at startup (bootstrap_node.js:149:9)
> >     at bootstrap_node.js:509:3
> 
> [10:09:47]  ngc: Compilation failed
> 
> [10:09:47]  ngc failed:  NGC encountered an error
> 
> [10:09:47]  Error: NGC encountered an error
>     at ChildProcess.<anonymous> (C:\Users\Adir\MyApps\tasklist\node_modules\@ionic\app-scripts\dist\ngc.js:62:24)
>     at emitTwo (events.js:106:13)
>     at ChildProcess.emit (events.js:191:7)
>     at ChildProcess.cp.emit (C:\Users\Adir\MyApps\tasklist\node_modules\cross-spawn\lib\enoent.js:40:29)
>     at maybeClose (internal/child_process.js:877:16)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
> 
> Error running ionic app script "build": Error: NGC encountered an error
> 
> npm
>  ERR! Windows_NT 10.0.14393
> npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Users\Adir\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js" "run" "build"
> npm
>  ERR! node v6.7.0
> npm ERR! npm  v3.10.8
> npm ERR! code ELIFECYCLE
> npm ERR! ionic-hello-world@ build: `ionic-app-scripts build --rollup ./config/rollup.config.js`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the ionic-hello-world@ build script 'ionic-app-scripts build --rollup ./config/rollup.config.js'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the ionic-hello-world package,
> npm
> ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     ionic-app-scripts build --rollup ./config/rollup.config.js
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs ionic-hello-world
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls ionic-hello-world
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     C:\Users\Adir\MyApps\tasklist\npm-debug.log
> 
> Caught exception:
>  undefined
> 
> Mind letting us know? https://github.com/driftyco/ionic-cli/issues
> 
> C:\Users\Adir\MyApps\tasklist>

**Comment by florianbepunkt** [comment]
This is not the same issue AFAIK. I had a compiling error with an unmodified clone of this repo. Please follow steps on the readme of this starter and check if error stills persists. If it doesn't, problem is with your code. 

This line should give you direction
`[10:09:47] ngc: Error: Error at C:/Users/Adir/MyApps/tasklist/.tmp/pages/login/login.ngfactory.ts:681:41: Property 'usersList' is private and only accessible within class 'LoginPage'.`

Try set `usersList` not to private… and I'm not sure why you have this /.tmp/ in your path. But maybe you better post this on SO, if this is not an issue with the starter itself.

**Comment by adirzoari** [comment]
thank you, i changed the property to public and now i get this error
C:\Users\Adir\MyApps\tasklist>ionic run android

```

Running 'run:before' npm script before run
> ionic-hello-world@ build C:\Users\Adir\MyApps\tasklist
> ionic-app-scripts build --rollup ./config/rollup.config.js
[10:28:14]  ionic-app-scripts 0.0.30
[10:28:14]  build prod started ...
[10:28:14]  clean started ...
[10:28:14]  clean finished in 31 ms
[10:28:14]  copy started ...
[10:28:14]  ngc started ...
[10:28:14]  lint started ...
[10:28:15]  copy finished in 213 ms
[10:28:15]  lint finished in 921 ms
[10:28:35]  ngc finished in 20.31 s
[10:28:35]  bundle prod started ...
[10:28:35]  bundle prod failed:  Could not resolve entry (/app/main.prod.ts)

[10:28:35]  Error: Could not resolve entry (/app/main.prod.ts)
    at C:\Users\Adir\MyApps\tasklist\node_modules\rollup\dist\rollup.js:8635:28
    at process._tickCallback (internal/process/next_tick.js:103:7)

Error running ionic app script "build": Error: Could not resolve entry (/app/main.prod.ts)



npm
 ERR! Windows_NT 10.0.14393

npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Adir\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.8
npm
 ERR! code ELIFECYCLE
npm ERR! ionic-hello-world@ build: `ionic-app-scripts build --rollup ./config/rollup.config.js`
npm ERR! Exit status 1
npm
 ERR!
npm ERR! Failed at the ionic-hello-world@ build script 'ionic-app-scripts build --rollup ./config/rollup.config.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ionic-hello-world package,
npm ERR!
 not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ionic-app-scripts build --rollup ./config/rollup.config.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ionic-hello-world
npm ERR! Or if that isn't available, you can get their info via:
npm
ERR!     npm owner ls ionic-hello-world
npm ERR! There is likely additional logging output above.



npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Adir\MyApps\tasklist\npm-debug.log

Caught exception:
 undefined

Mind letting us know? https://github.com/driftyco/ionic-cli/issues


C:\Users\Adir\MyApps\tasklist>






```

**Comment by kornatzky** [comment]
If the Ionic CLI cannot find `/app/main.prod.ts`, it means it was not build. This implies there was a compilation error. Since you are not getting any syntax error above it, I would suggest starting with
`ionic serve' and see what errors you get and post them here

**Comment by adirzoari** [comment]
@kornatzky  thank you for you time,
i have not errors while i run ionic serve but i can see the page only in explorer browser, in chrome- not
you can see
 i run ionic info i get is

Your system information:

Cordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-rc.0
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
OS:
Node Version: v6.7.0
i add the photo i compare between chrome and explorer
i have the latest version in chrome and it not works, but in explorer it works.
![comp](https://cloud.githubusercontent.com/assets/20258998/19267093/8210ed84-8fb5-11e6-8e3b-58c2031b7b44.png)

**Comment by kornatzky** [comment]
A trivial advice, you probably already did it. Clear browser history in Chrome and restart Chrome. Are you on Windows 10?

**Comment by adirzoari** [comment]
yes in windows 10

**Comment by kornatzky** [comment]
Are you willing to share your code, just the src and www, without the node modules. I presume you did do much coding yet. Thanks

**Comment by adirzoari** [comment]
yes,
first i just want to tell you the chrome works now after i clear browser history, so thank you.
the issue now is when i run ionic run android

i upload this file here
[http://www.filedropper.com/tasklist](url)
)

**Comment by kornatzky** [comment]
Are you using this library for the Firebase import:

https://www.npmjs.com/package/firebase

?

**Comment by adirzoari** [comment]
yes i installed by 

> $ npm init
> $ npm install --save firebase

**Comment by adirzoari** [comment]
@kornatzky did you find any wrong with my code?

**Comment by kornatzky** [comment]
So far discovered the following: In Chrome with `ionic serve` and in Android with `ionic run android`, we see this error: 
Uncaught TypeError: Cannot read property 'navigator' of undefined
This occurs a result of Firebase in `firebase/app.js`
This prevents the your app from running, showing a blank screen. 
Are you sure we are talking about the right dependency?

**Comment by adirzoari** [comment]
@kornatzky yes,
i had this error before but i solved it but changed with this tutorial
http://alexmgrant.github.io/ionic/firebase/rc0/lodash/2016/10/06/ionic-rc0-&-firebase.html

**Comment by kornatzky** [comment]
Following the Firebase tutorial. Will let you know.

**Comment by kornatzky** [comment]
The issue was reproduced on Android. It seems to be due to the Firebase construction of rollup config. The app as generated fresh from the starter was alright on Android. So my conclusion is the instructions for building the app with Firebase cause it to fail. This is something in which unfortunately I cannot help. Suggest you contact Firebase.

The error log that I got is::

kornatzkys-MacBook-Pro:zoari kornatzky$ ionic run android 

Running 'run:before' npm script before run

> ionic-hello-world@ build /Users/kornatzky/Downloads/zoari
> ionic-app-scripts build --rollup ./config/rollup.config.js
> [16:48:32]  ionic-app-scripts 0.0.30
> [16:48:32]  build prod started ...
> [16:48:32]  clean started ...
> [16:48:32]  clean finished in 32 ms
> [16:48:32]  copy started ...
> [16:48:32]  ngc started ...
> [16:48:32]  lint started ...
> [16:48:34]  copy finished in 2.46 s
> [16:48:41]  lint finished in 8.64 s
> [16:49:51]  ngc finished in 79.38 s
> [16:49:51]  bundle prod started ...
> [16:49:52]  bundle prod failed:  Could not resolve entry (/app/main.prod.ts)

[16:49:52]  Error: Could not resolve entry (/app/main.prod.ts)
    at /Users/kornatzky/Downloads/zoari/node_modules/rollup/dist/rollup.js:8635:28

Error running ionic app script "build": Error: Could not resolve entry (/app/main.prod.ts)

npm
 ERR! Darwin 16.0.0

npm ERR! argv
 "/usr/local/Cellar/node/6.7.0/bin/node" "/usr/local/bin/npm" "run" "build"
npm 
ERR! node v6.7.0

npm ERR! 
npm  v3.10.8
npm ERR!
 code ELIFECYCLE
npm ERR! ionic-hello-world@ build: `ionic-app-scripts build --rollup ./config/rollup.config.js`

npm ERR! Exit status 1

npm ERR! 

npm ERR! Failed at the ionic-hello-world@ build script 'ionic-app-scripts build --rollup ./config/rollup.config.js'.
npm
 ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ionic-hello-world package,
npm 
ERR! not with npm itself.
npm 
ERR! Tell the author that this fails on your system:
npm ERR!     ionic-app-scripts build --rollup ./config/rollup.config.js

npm ERR! You can get information on how to open an issue for this project with:

npm 
ERR!     npm bugs ionic-hello-world
npm ERR! Or if that isn't available, you can get their info via:
npm
 ERR!     npm owner ls ionic-hello-world
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/kornatzky/Downloads/zoari/npm-debug.log

Caught exception:
 undefined 

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

kornatzkys-MacBook-Pro:zoari kornatzky$

**Comment by adirzoari** [comment]
@florianbepunkt thank you very much! apperciate your time
