### ISSUE TITLE
Working fine ionic serve 404 on api calls on android device

### ISSUE THREAD

**Issue by chris-munn** [backand/backand-ionic2-starter#5]
Thank you ever so much for the repo, I have been working in ionic serve and completely blown away by how powerful this is.

Current problem though is when I run on a device (android galaxy s5) I get error son all the api calls.

404 Not Found

this is on all of these and other auth ones too:

https://api.backand.com/1/objects/items?returnObject=true
https://api.backand.com/token

**Comment by chris-munn** [comment]
Ok so i found the issue, in rc.0 of ionic you need to install cordova whitelist plugin:

cordova plugin add cordova-plugin-whitelist

Then add relevant info in meta tag within your www/index.html file

`<meta http-equiv="Content-Security-Policy" content="script-src 'self' 'unsafe-eval' 'unsafe-inline' *; object-src 'self'; style-src 'self' 'unsafe-inline'; media-src *">`

This should be included in the setup documentation as took me a good couple of hours to debug this.

Credit for this fix was found here: http://www.gajotres.net/ionic-2-making-rest-http-requests-like-a-pro/

**Comment by kornatzky** [comment]
I just constructed a fresh new Ionic project with their base starter. It installs the whitelist plugin. So you do not need to do an explicit installation. My Ionic version is 2.1.4. For us the `meta` change was not needed. As far as I know, this default: 

```
`  <access origin="*"/>`
```

in config.xml is enough
